#!/bin/sh
### BEGIN INIT INFO
# Provides:          gymon
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       TCP server used for querying Gymea services
### END INIT INFO

SCRIPT=/home/wbuckley/projects/gymon-make/gymon.out
RUNAS=root
LOGFILE=/var/log/gymon.log

start() {
  if pgrep -x "gymon.out" > /dev/null
  then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\""
  if sudo sh -c "$CMD" $RUNAS true 2>/dev/null; then
   echo 'Service started' >&2
  else
   echo 'Failed to start gymon service' >&2
  fi
}

stop() {
  if pgrep -x "gymon.out" > /dev/null
  then
    echo 'Stopping gymon service...' >&2
    sudo kill -15 $(pgrep -x "gymon.out") && echo 'Service stopped' >&2
    return 0
  fi
    echo 'gymon service is not running' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
