#!/bin/sh
### BEGIN INIT INFO
# Provides:          gymon
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       TCP server used for querying Gymea services
### END INIT INFO

SCRIPT=/opt/delphax/gymon/bin/gymon.out
RUNAS=root
LOGFILE=/var/log/gymon/gymon.log
TRUE=0
FALSE=1

status() {
  if pgrep -x "gymon.out" >/dev/null; then
    return ${TRUE}
  else
    return ${FALSE}
  fi
}

start() {
  if status; then
    echo 'Service already running' >&2
    return ${FALSE}
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\""
  if sudo sh -c "$CMD" $RUNAS true 2>/dev/null; then
   echo 'Service started' >&2
  else
   echo 'Failed to start gymon service' >&2
  fi
}

stop() {
  if status; then
    echo 'Stopping gymon service...' >&2
    sudo kill -15 $(pgrep -x "gymon.out") && echo 'Service stopped' >&2
    return ${TRUE}
  fi
    echo 'gymon service is not running' >&2
    return ${FALSE}
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    if status; then
      echo "gymon service running"
    else
      echo "gymon service stopped"
    fi
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
esac
